Vagrant.configure("2") do |config|
  config.vm.define "smbarkiS" do |server|
    server.vm.box      = "debian/trixie64"
    server.vm.hostname = "smbarkiS"
    server.vm.network :private_network, ip: "192.168.56.110"
    server.vm.provider :libvirt do |lv|
      lv.default_prefix = ""      # domain is named smbarkiS, not p1_smbarkiS
      lv.memory = 1024            # subject p6: 512 MB or 1024 — the server gets 1024
      lv.cpus   = 1               # subject p6: 1 CPU
    end
  end
end
